package hieusenpaj.com.thuecanhan.`object`

import java.io.Serializable

class KhaiThue(
    var p1: String,
    var p2: String,
    var p3: String,
    var p4: String,
    var p5: String,
    var p6: String,
    var p7: String,
    var p8: String,
    var p9: String,
    var p10: String,
    var p11: String,
    var p12: String,
    var p13: String,
    var p14: String,
    var p15: String,
    var p16: String,
    var p17: String,
    var p18: String,
    var p19: String,
    var p20: String,
    var p21: String,
    var p22: String,
    var p23: String,
    var p24: String,
    var p25: String,
    var p26: String,
    var p27: String,
    var p28: String,
    var p29: String,
    var p30: String,
    var p31: String,
    var p32: String,
    var p33: String,
    var p34: String,
    var p35: String,
    var p36: String,
    var p37: String,
    var p38: String,
    var p39: String,
    var p40: String,
    var p41: String,
    var p42: String,
    var p43: String,
    var p44: String,
    var p45: String,
    var p46: String,
    var p47: String,
    var p48: String,
    var p49: String
) :
    Serializable {
}